FROM apache/spark:3.5.1

USER root

# ===============================
# Install Python deps
# ===============================
RUN apt-get update && \
    apt-get install -y python3-pip && \
    pip3 install --no-cache-dir redis && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# ===============================
# Download Spark Kafka connectors
# ===============================
RUN curl -L -o /opt/spark/jars/spark-sql-kafka-0-10_2.12-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-sql-kafka-0-10_2.12/3.5.1/spark-sql-kafka-0-10_2.12-3.5.1.jar && \
    curl -L -o /opt/spark/jars/spark-token-provider-kafka-0-10_2.12-3.5.1.jar \
    https://repo1.maven.org/maven2/org/apache/spark/spark-token-provider-kafka-0-10_2.12/3.5.1/spark-token-provider-kafka-0-10_2.12-3.5.1.jar && \
    curl -L -o /opt/spark/jars/kafka-clients-3.6.0.jar \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka-clients/3.6.0/kafka-clients-3.6.0.jar && \
    curl -L -o /opt/spark/jars/kafka_2.12-3.6.0.jar \
    https://repo1.maven.org/maven2/org/apache/kafka/kafka_2.12/3.6.0/kafka_2.12-3.6.0.jar && \
    curl -L -o /opt/spark/jars/commons-pool2-2.11.1.jar \
    https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.11.1/commons-pool2-2.11.1.jar

USER spark